### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'h2'

### ISSUE THREAD

**Issue by prasad01dalavi** [shubhamc183/way2sms#4]
```
Traceback (most recent call last):
  File "C:\Users\Prasad\Desktop\security_serveillance\Server\security_serveillance\test_sms.py", line 9, in <module>
    sent_count = message.msgSentToday()
  File "C:\Users\Prasad\Desktop\security_serveillance\Server\security_serveillance\my_sms.py", line 55, in msgSentToday
    self.t = self.soup.find("div", {"class": "hed"}).h2.text
```

**Comment by prasad01dalavi** [comment]
got it. solved by changing the site url. from site24 to site21. it took hello lot of time to figure it out. because it was working fine earlier.
